name: Deploy to GitHub Pages via angular-cli-ghpages
on: [push]
  branches: [ main ]
jobs:
  build-and-deploy:
  runs-on: ubuntu-latest
  env:
    REPO_HREF:  '/bug-free-lamp/'
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
    - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run lint
          npm run ng -- deploy --base-href=${{ REPO_HREF }} --name="deploy-bot" --email=deploybot@example.org
